# Security
app_login:
  path: /login
  controller: App\Controller\SecurityController::login
  methods: GET|POST

app_logout:
  path: /logout
  methods: GET

# Homepage
app_home:
  path: /
  controller: App\Controller\HomeController::dashboard