# Security
app_login:
  path: /login
  controller: App\Controller\SecurityController::login
  methods: GET|POST

app_logout:
  path: /logout
  methods: GET

# Notebook
app_notebook_new:
  path: /notebook/new
  controller: App\Controller\NotebookController:new

# Task
app_task_new:
  path: /task/new
  controller: App\Controller\TaskController:new

app_task_view:
  path: /task/{taskCode}
  controller: App\Controller\TaskController:view

# Homepage
app_home:
  path: /{weekCode}
  controller: App\Controller\AppController:home
  defaults:
    weekCode: ''